### ISSUE TITLE
Use external URL for Query details link

### ISSUE THREAD

**Issue by purewell** [trinodb/trino-gateway#280] opened 2024-03-14 02:14 UTC
Query details link doesn't use externalUrl property.

If externalUrl is set, query detail link uses externalUrl.

![image](https://github.com/trinodb/trino-gateway/assets/6290526/37b127cc-0174-4b98-bbc6-15cd1dee5410)

**Comment by ebyhr** [comment] 2024-03-14 22:08
Closing as duplicate of https://github.com/trinodb/trino-gateway/issues/81

**Closed by ebyhr** 2024-03-14 22:08 UTC
Labels: ui
